# This is a config for E2B sandbox template.
# You can use template ID (xb5vu76au4wv53xrh5gi) or template name (vibeai-nextjs-test-01) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox.create("vibeai-nextjs-test-01") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibeai-nextjs-test-01") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibeai-nextjs-test-01')

team_id = "bb9b9f4f-5033-4ed0-a337-d806eed18efa"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibeai-nextjs-test-01"
template_id = "xb5vu76au4wv53xrh5gi"
